# Generated by Django 4.0.4 on 2022-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_content_en_post_content_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='value_en',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='value_ru',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=8, null=True),
        ),
    ]
